### ISSUE TITLE
Some icons need restart when selecting theme

### ISSUE THREAD

**Issue by rodrigoccurvo** [baumgarr/nixnote2#103]
The icons of the actions for Email and New Note do not load when selecting a theme, they remain the ones when you first opened Nixnote. Only if you restart Nixnote it will load the ones from the selected theme.

**Comment by baumgarr** [comment]
I added the email icon, so it should work after the next release.

There doesn't seem to be a good way to fix the new note icon.  The problem is that it is a drop down list of three different icons.  The icon is updated in the drop down but the current selection in the button group isn't updated.  You can see that it is updated by dropping down the selection.  To update it you'll need to re-select the note from the drop down or select a different action, then re-select the new note.  That changes the top level icon.
