### ISSUE TITLE
Again few notes saved with white font color when dark theme enabled

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#124]
And in Android I "see" white text on white background.

I remember that you said that theme not affect notes color, but this is real bug

**Comment by baumgarr** [comment]
Extract the note & attach it.  I can't recreate so I'll need an example.

**Comment by baumgarr** [comment]
Yes.  The error is this:

Element or attribute do not match QName production: QName::=(NCName':')?NCName. " 

You'll need to look at the source & try to find what that means.  I'm guessing that you copied this from a web page & the paste had some strange HTML in it.  You can try extracting the note & sending it to me or you can wait until the next release.  I'm working on some logic to be more strict in cleaning things like this up.

**Comment by vitaly-zdanevich** [comment]
This is the source of problem note, as we see `font-color=#FFF` but this is not me. I copied content of this note from Firefox and from terminal at Debian.

GitHub at comments cut html tags so look here http://paste.ubuntu.com/14003941/

**Comment by baumgarr** [comment]
I don't think there is anything I can do to correct this without running the risk of removing formatting.  The problem is that whatever is pasting it is inserting setting the font color as white for the text and not using the default font color of the editor.  Because of this the white is not being removed.  I can't tell the difference between what is pasted and what a user specifically wants changed.  

Even doing what you described,  I can't recreate this so I don't think NixNote is doing this directly.  About the only thing I can recommend is to do is to try pasting it as unformatted text and see if that helps.  Otherwise, don't use the dark theme when pasting.
