### ISSUE TITLE
please add the ability to export all notes as text where note=file; from terminal

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#126]
Will be great to use this with `cron` for backup to `git` where user can see the `diff`

**Comment by baumgarr** [comment]
I'm not sure I understand.  Could you give me a detailed example?

**Comment by vitaly-zdanevich** [comment]
Would be great to have as a result folder with files like `my note about flowers.txt`, `my note about dogs.txt`, and inside of every text file user can see the content of note

**Comment by baumgarr** [comment]
You can accomplish that with a series of shell commands.  For example:

nixnote2 query --noHeaders --search="flowers" --delimiter=" " --display=%i%t | awk  '{ print "nixnote2 readNote  --id=" $1 " | fold -w 80 -s > "$2"_"$1".txt"}' | sh

That is rough, but it will do what you want and wrap lines at 80 characters.  I'm not the world's expert on shell scripts.  :-)

I wouldn't recommend doing something like this with NixNote running because it will probably slow down the GUI to a crawl (but in theory it should work).

**Comment by vitaly-zdanevich** [comment]
As I see this script search for note `flowers` - but how can I export full database?

**Comment by baumgarr** [comment]
Don't specify the --search parameter.  If you don't specify it, you get everything.  The query command line works the same as the search box in the GUI.  If you don't specify a search string you get everything.

**Comment by vitaly-zdanevich** [comment]
great, thank you for the script, but in exported files I see `Â Â  Â` for new-line symbol. Is it possible to handle new-lines? And also many files have `????` at name instead of Russian symbols. And as I see generated text files have not the full name of note but only the first word.

**Comment by baumgarr** [comment]
I was just using that command as a simple example to show extracting the contents of a note.

If you use the note's title there would be checking that would need to be done depending on what notes you are extracting.  For eample, a note with the title of "http://www.google.com" would fail because that isn't a valid Linux file name.  If nothing else, you could write the query to a text file and read it in a shell script where you could cleanup the names (or you could use something other than the note's title as the file name).  

However, if you want the full title as the file name you could do something like this:

nixnote2 query --noHeaders  --display=%i%t |  awk -F '|' '{ gsub(" ","_",$2);  print $1 $2; }' | awk  '{ print "nixnote2 readNote --id=" $1 " | fold -w 80 -s >> "$2"_"$1".txt"}' | sh

Once you have it extracted to a file you can do whatever you want to the carriage control symbols using sed or any other command line tools.  

You opened a ticket on the ???? for Russian symbols already and it should be fixed in the next release.

**Comment by baumgarr** [comment]
I should also add, that the ability to create a NixNote extract is also in the next release, but (unlike the query) you do need to specify some type of search string or a note's ID.  A backup via the command line (also in the next release) will extract everything.

**Comment by vitaly-zdanevich** [comment]
Thank you for help :+1:

**Comment by 1xPdd** [comment]
@baumgarr, I tried the script:
`nixnote2 query --noHeaders --display=%i%t | awk -F '|' '{ gsub(" ","",$2); print $1 $2; }' | awk '{ print "nixnote2 readNote --id=" $1 " | fold -w 80 -s >> "$2""$1".txt"}' | sh`
While it works for some notes, most notes are empty. Any ideas?

> I should also add, that the ability to create a NixNote extract is also in the next release, but (unlike the query) you do need to specify some type of search string or a note's ID. A backup via the command line (also in the next release) will extract everything.

This is awesome news. I'm really looking forward to this.
