### ISSUE TITLE
preferences: default editor font size & default GUI font size: empty dropdowns

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#129]
Debian 8

also I dream about option where I can set only **visible** font size for note - I want to set large, maybe 20, but in the database was kept normal size - and in Android I also can correct read my notes

**Comment by baumgarr** [comment]
Right now, the best option would be to edit the /usr/local/nixnote2/qss/editor_dark.css in the install directory.  You can alter the font size or colors and it "should" be local to nixnote as long as you are using the dark editor theme.  Alternatively you can create your own theme, but that is still a little buggy.  You'll also want to save any changes because future updates can overwrite this file.

**Comment by vitaly-zdanevich** [comment]
yes, I set `font-size: 30px` for my big display!
