### ISSUE TITLE
Unable to backup or import nixnote 2 6

### ISSUE THREAD

**Issue by catski** [baumgarr/nixnote2#146]
Firstly a HUGE thank you for nixnote, very much appreciated.
I upgraded to nixote 2 - 5 and cannot restore or import notes. The first box shows the number of notes being imported and the numbers whiz through. The second says "restoring notes" and it hangs on that and nothing happens. There is no evidence anything is imported. You can cancel the restoring notes window and continue using nixnote.

I found other reports of this so enabling debug etc shows this
[messages.txt](https://github.com/baumgarr/nixnote2/files/83617/messages.txt)

Thank you for helping with this. I will try installing 2 - 6 and see if there is any difference

**Comment by baumgarr** [comment]
Glad you find it useful.  Just as an FYI, the latest version is beta 7.  This bug is (hopefully) fixed in the next release.  

If it isn't fixed in the next release please re-open this issue.  To get me the information I need please set the message level to "trace".  That will produce a lot more output but will help me narrow down the issue.

Thanks.
