### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by komitaltrade** [baumgarr/nixnote2#152]
Arch x64 - Cinnamon DE - Nixnote beta 7

Compliments, now it looks and works quite nice.

1) When I assign two accounts, I have two active tray icons (I like that). Is it possible to assign to account tray icon specific color? Now both icons are gray and user should to guess account.

2) Show/Hide from tray not works (for me), more precise, hide works and show not. Double click on tray also not open note. Only option is to close it and that to open apps one more time or just simply to click on i.e. desktop icon again to show it (tray icon remain in tray).

3) It looks that Open note in new tab not works also. Open in new windows works well. Open note probably should to be renamed to Edit note as it appear editable in main dialog.

**Comment by baumgarr** [comment]
1) You should be able to do this, but you'll need to use a different theme to specify the tray icon.  Look at the theme.ini in the install directory or look at the user manual for more information.

2.) It won't work with all window managers because of the signals they are sending.  I haven't found a workaround yet and there are enough window managers to make it difficult.

3.) Opening a note in a new tab will only work if the note isn't open in the main dialog.  In other words, you can't have the same note open in two tabs.

**Comment by komitaltrade** [comment]
1) I think that you didn't understand me (I made review of your reply, manual and theme.ini). I'm talking about TWO DIFFERENT ACCOUNTS and two different tray icons (to assign it per account). I have several Evernote accounts (different purposes) and I like that Nixnote support it very well. My issue is when I have opened in SAME TIME more than one account (usually not less than two), I have in my tray TWO SAME COLORIZED ICONS. I would like if I can assign colors per account (generally, not just tray icon) to be able more easy to switch accounts.

2) Yes, I figured that also from our previous communication (issue) on git, but here is about that how before Show/Hide in Cinnamon worked and now not.

However, this is not some very important issue, as it is possible to solve it via keybindings (and works well for me), what is basically also much faster that click on tray icon menu item Show/Hide.

3) Thanks. Yes it works exactly like you indicated in reply.

P.S. I think that you are now mainly "mature" to cease "beta" and to launch it like regular apps, as I really use it and I didn't found any other real issue. Nice work and thanks for great app!

Yeah, please see that with "coloraizing accounts", what is not a issue, rather feature request.

P.S. - 1 - Do you think about translation? I guess that I can help with several languages.

**Comment by komitaltrade** [comment]
In fact, SHow/Hide issue appear only if in Preferences is enabled "Close to tray". So, if Nixnote is minimized to tray, Show/Hide (and click on tray icon) works well. If Nixnote is closed first time, also works. If it is closed second time (in session) it not works (but than it can be launche from ie desktop/panel/menu icon or hotkey.

**Comment by baumgarr** [comment]
I think you may be the only person other than myself who has commented that they use multiple accounts.  

I may not have explained myself very well (or I'm being very slow in understanding what you are asking).    I don't have anything setup to do per-account coloring of the tray icons, but you can create a copy of the icon and color it however you want.  Then just save it to a new name & create a new theme with it.

The themes are per-account, so you can have two separate themes for two separate accounts.  Part of the theme specifies the tray icon, so by having two separate themes you can have two different tray icons.  You'll need to create your own theme because I don't think any have tray icons specified as part of the theme, but it should work.  You'll just need to copy an existing theme, give it a new name, and add this line:

trayIcon=path-to-your-icon.png  

To keep your theme from being overridden when you upgrade, copy the theme.ini to ~/.nixnote/ and just put your new theme in there.   Also note that there is a typo in the example.   It has the tray icon specified as trayiconIcon, it should just be as I show above.

Once you have the new theme created, pick one of the accounts and go into "Edit/Theme" and choose your new theme.  You may need to restart it to make it take effect, but I tested it and it works for me.  One account will have the old theme & icon, and the other will have the one you specified.

I'm glad you think it is stable enough to drop the beta.  It is close to that point.  There are really one major bug that is keeping it in beta.  I think I have it fixed for the next beta so hopefully that will be the last beta (but I've also been saying that since beta 3).  

If you want to do any translation work I'd appreciate the help.  Qt Linguist is what is used for translations to different languages.  You can look in the translations directory for examples on what others have done.

Thanks,
Randy

**Comment by komitaltrade** [comment]
1) Yeah, I agree how that is not exactly "regular" situation, but in my circumstances I should to have it.
Idea with theme per account is great. Unfortunatelly its not works (on my pc). It is usual approach to "play" with home folder (to not affect updates) and I figured your instructions well. But it not works.
Also, your theme.ini have trayiconIcon instead of trayicon. 
So, I duplicate classic theme and renaimed it (theme appear in menu). Than I just added line with trayicon (all variants) containing path to image placed within new image folder created ~/.nixnote/images/ with 24px and png extension. But ....
2) About beta. Correct, as I don't use too much many options, just simple note taking, I didn't noticed any issue in those basic functionalities (it could be some others, I don't know). Originally, I worked with combination of chrome apps and wine version, but now (from beta 7) I replaced it with Nixnote.
3) I recently installed it on two pc's, one was in German (Mint Cinnamon), but it appear in English. Why?

**Comment by baumgarr** [comment]
Paste your theme here & I'll see what is wrong.  I tested it and it works for me.  You need to give the theme a new name, or you're just overriding the existing theme.  Once you define a new theme, you then need to select it under Edit/Theme.

As for the translations, it gets the locale from the system and then tries to find a translation file for it.  If you set the message level to "Debug" under Edit/Preferences and restart, you'll see a message that starts with "Looking for translations:" followed by the translation name it is trying to find.

**Comment by baumgarr** [comment]
No response.  Closing.
