### ISSUE TITLE
Access media attachments from commandline?

### ISSUE THREAD

**Issue by sunjam** [baumgarr/nixnote2#174]
Is there currently a way to access just media attachments from the commandline?

I'd like to open specific images in a different program to view and edit.
I'd also like to access audio recordings to listen to from a different application.

**Comment by baumgarr** [comment]
There is not a way to do this currently. I could add a query option to find all of the attachments for a note and then you can find them in ~./nixnnote/db-1/dba directory, but you wouldn't want to edit them using another program. Each attachment has a checksum and by editing it you'll change it. That will probably cause issues when you sync.

**Comment by sunjam** [comment]
What about a way to "Save attachment" from the cli.  I locate the media object, copy it to a specified directory, and edit the copy.

This would prevent the sync issue, yes?

**Comment by baumgarr** [comment]
There isn't any easy way to find what attachment belongs to a particular note. That isn't something I ever expected.  You could find it via a Sqlite query to the DB once you had a note's ID, but if there were more than one attachment you'd need to know which one you needed.

Also, the attachments are not stored directly in the database, but are in ~/.nixnote/db-x/dba directory (db-x is separate for each account). 

The query you need would be something like this:
"select lid from datastore where key=6001 and data=<the_id_of_the_note>;"

That will give you the ID number of the resource and you could then find any file starting with that ID in the dba directory (It will have a different extension based upon the file type).

Even if you did find the resource and make another copy, the original copy couldn't be replaced without messing things up for that note because the hash value would have changed. About the best you could do is to then save the attachment in some type of import folder or create another new note via the command line. That seems like a lot of work.

**Comment by baumgarr** [comment]
No response. Closing issue. Please reopen if you have another question.
