### ISSUE TITLE
Questions about nixnote2 dependencies and development

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#183]
Hi,

I just adopted an RFP and converted it into [ITP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=609849) on Debian BTS. Putting nixnote2 into Debian may be challenging but possible. I am willing to take a try and work for it later.

There are several questions and problems, though, as listed below:

1. Looks like the split of webcam plugin is not working correctly currently (see #182). OpenCV is indeed a big problem, and Debian is preparing the [2->3 transition](https://release.debian.org/transitions/html/auto-opencv.html) as well. I may not enable webcam feature for now till the situation becomes clear.

2. The default debian package is listing `libreoffice-common` in `Recommends:` section, which made `apt` install the huge libreoffice-related stuff into system. I read through the user documentation pdf but found no word about libreoffice. So I am wondering the actual function of libreoffice-common in nixnote2, and what will happen if it does not exist in the system. If libreoffice only provides minor features, it would be much better to move it into `Suggests:`. 

    The same situation applies to `cups`, `mimetex` and `java`. My preference is to move every optional dependency to `Suggests:` except `mimetex` due to its small size and simple dependency.

3. As for the choice of Qt version, I personally prefer Qt5, but there seems to be some extra bugs (see stderr output and github issues). I strongly suggest the complete port and test onto Qt5 since Qt4 is already in EOL state.

Thanks.

**Comment by baumgarr** [comment]
Hello,

I'm not sure what an ITP is.

As for your questions...

1.) Yes. It is a bug. It will take another release to correct it. NixNote will work fine without the plugin. I doubt a whole lot of people use it. I also would like to put Hunspell in a separate plugin is well (eventually) to keep that dependency at a minimum.

2.) libreoffice-common can be removed. It is an oversight. At one point I used it to parse the text from attachments like Word or Excel, but the overhead of starting & stopping it for every single attachment became too much. If I remember, I have that section of code commented out. I'll remove it from the next beta.

Java is only needed to encrypt or decrypt notes. Without Java, NixNote will still work but that functionality won't be available.

Cups is needed for printing.

Mimetex is only needed if someone wants to add LaTeX formulas to a note. NixNote will still work without it, but that feature won't be available.

I can change them to suggest. It doesn't make me any difference. 

As for moving to Qt5, that will happen eventually. Probably sooner rather than later. I wanted to keep a common version of Qt rather than fighting new bugs with every Qt release until NixNote is out of beta, but I had hoped to be out of beta about a year or two ago.

Thanks,
Randy

**Comment by hosiet** [comment]
Thanks for your reply. You may look at Debian bug #609849 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=609849) for ITP history and detail.

**Comment by hosiet** [comment]
Hi,

I am looking through your source code and found one more problem:

* The `/certs/` directory seems contains some certificates, which may cause licensing issues. What is the purpose of certificates, and is it possible to remove them from the source code without harming nixnote2 core functions? (e.g, try to obtain the certificates from system first and depend on `ca-certificates` from the system?)

**Comment by baumgarr** [comment]
That is a leftover from some earlier development. It isn't needed and I'll remove it for the next release.
