### ISSUE TITLE
Thumbnailer not working

### ISSUE THREAD

**Issue by MagnusWestin** [baumgarr/nixnote2#189]
I have just made a new sync against my pro evernote account, and I dont get any thumbnails.

I checked the datastore table, and I dont have any entries with 5997 (NOTE_THUMBNAIL_NEEDED). Not sure why that is, if I understand the code, it should create an entry for each note while syncing with that number.

I also tried against a much smaller free account, same problem there. I shutdown the client as soon as the sync was done, and I didn't have any entries in datastore with key 5997.

**Comment by baumgarr** [comment]
This should be fixed in the next release. I forgot I had disabled this a while back to work on a different bug. 

This is how it works:
- If there are no notes that need a thumbail or if there is a sync in progress it will check to see if a thumbnail is needed every 60 seconds.
- If a thumbail is not needed, it goes back to sleep for 60 seconds.
- If a thumbnail is needed it generates it, and goes to sleep for 5 seconds. If I do it any more frequent it seems to impact performance. 

I'll probably make these values alterable in the future, but right now this seems to work best. 

Please note: Any existing notes without thumbnails won't be re-generated, but newly downloaded ones & altered ones should generate. 

If you need them all to be regenerated, you can issue this command against the database using sqlite3.

"insert into datastore (lid, key, data) select distinct lid, '5997, '1' from datastore;"

DO NOT DO THIS UNTIL THE NEXT BETA. It has the potential of causing NixNote to constantly re-generate the same thumbail every 5 seconds forever in the current beta.

Thanks!
