### ISSUE TITLE
Nixnote2 sometimes loses text when a tab is closed, in some cases erasing contents entirely

### ISSUE THREAD

**Issue by justyn** [baumgarr/nixnote2#203]
I have suffered with this problem for a while but have waited to see if it would clear up in a new build or if it would be reported by someone else.
I have seen it on several beta builds, and most recently with daily+20160823. On Ubuntu 16.04.

Sometimes when I close a tab I lose recent editing/typing in the note. Often I don't notice right away. In some cases (and I'm assuming this is the same bug) I find that a note I want to go back to is completely blank, which is very frustrating.

I can reproduce, but only by repeatedly editing a note in a tab and closing it, until the bug happens.

Steps to reproduce:
1) Open a note in a new tab, and add some text.
2) Close tab with ctrl-w.
3) Open same note in new tab
4) Repeat steps 1 to 3 until added text is not saved.

Can I give any more helpful info?

**Comment by rmorbor** [comment]
I have also experienced the exact same problem, but rather than see the issue while closing a TAB I've experienced it while closing the entire application. 

I'm also using Ubuntu 16.04 and I'm running nixnote2 as sudo user

Adding the this information in case is helpful towards this problem resolution

**Comment by baumgarr** [comment]
I think I have this fixed in the next beta. It should be out in 3 days. Please reopen it if you still have issues.
