### ISSUE TITLE
RPM package for beta10

### ISSUE THREAD

**Issue by smesterheide** [baumgarr/nixnote2#213]
Can you please provide RPM packages? I can't seem to find them on Sourceforge. Much appreciated!

**Comment by agunn-mc** [comment]
Just ran across this - https://copr.fedorainfracloud.org/coprs/nunodias/nixnote2/

**Comment by artmg** [comment]
Well spotted, @agunn-mc ! 

The [Copr package you found](http://copr-dist-git.fedorainfracloud.org/cgit/nunodias/nixnote2/nixnote2.git/tree/) takes its source directly from github archives (and the MD5 matches) so I figure it's trustworthy. What's great is that it's on Copr, fedora's community autobuild repos, that are easy to add using the command `dnf copr enable nunodias/nixnote2`

If any Fedora or CentOS user could please validate the package is working ok, then we can add this to the documentation - yet more easy ways for users to benefit from @baumgarr and the team's excellent work.

This package is one of a number that have been created by Nuno Dias for Fedora during the past year or so. Scanning through the "Nuno Dias"es active on github, I'm not sure that he's one of them, but his email address appears in the Fedora system, so I'll drop him a line to say thanks!

**Comment by jeffbuhrt** [comment]
nixnote2-2.0_beta10-3.ndias.fc25.x86_64 seems to have been working fine for the last two weeks.

Name        : nixnote2
Version     : 2.0_beta10
Release     : 3.ndias.fc25
Architecture: x86_64
Install Date: Tue 29 Nov 2016 11:58:25 AM EST
Group       : Applications/Internet
Size        : 9341871
License     : GPLv2
Signature   : RSA/SHA1, Mon 28 Nov 2016 09:37:51 AM EST, Key ID 79acf02735d64b40
Source RPM  : nixnote2-2.0_beta10-3.ndias.fc25.src.rpm
Build Date  : Mon 28 Nov 2016 09:37:47 AM EST
Build Host  : copr-builder-786556416.novalocal
Relocations : (not relocatable)
Vendor      : Fedora Project COPR (nunodias/nixnote2)
URL         : https://github.com/baumgarr/nixnote2
Summary     : Evernote client clone for Linux

**Comment by artmg** [comment]
Created [Pull Request](https://github.com/baumgarr/nixnote2/pull/241) for RPM installation instructions in git README front page.

Issue ready to close

**Comment by baumgarr** [comment]
I've uploaded RPMs for Beta 11 on SourceForge. If I messed them up please let me know.  Sorry for the delay.

**Comment by jeffbuhrt** [comment]
@baumgarr:

1) Your Fedora x86_64 build seems to be working well. [Except for a very minor #4 below]

2) FYI: The https://copr.fedorainfracloud.org/coprs/nunodias/nixnote2/ build shows: 
Build: 488989
State: failed
Finished: 15 days ago

3) The tag not setting issue #235 (#161 original) is fixed in beta11 like you thought.

4) If I maximize/minimize on a 2nd monitor, the dropdown menus appear about 1/4 of the way down the screen vs attached to the menubar. If I drag the window back to the primary monitor it is fine, but remains detached when on the secondary monitor. This is the simplest way to always repeat this. [I have seen it in a few other cases, but I haven't figured out how to repeat it.]
-I don't see any errors/messages in the Debug level log nor in the command line (stdout/stderr) when started from the command line. I assume it is a Qt thing.
-Let me know if you want more info, a screenshot, and/or a new ticket to hold this.

Thanks again for the hard work!
