### ISSUE TITLE
nixnote是否可以优化网络代理功能

### ISSUE THREAD

**Issue by omaidb** [baumgarr/nixnote2#217]
一般我们都会使用国际版evernote账户，不过这有个缺点，就是在中国大陆使用的话，同步速度会非常慢，所以一般国内用户都会自备梯子--使用代理，我使用的shadowsocks，在nixnote设置选项中找了，似乎没有socks5的代理选项，希望增加该代理模式，因为现在同步速度实在太慢了。

**Comment by hosiet** [comment]
Let me translate for this issue.

Title: Could nixnote add function to set up network proxy
Content: Normally we need a international version evernote account to use nixnote. However, there is a disadvantage here. When using evernote in China mainland, the sync speed would be really slow. As a result, most users in China mainland would decide to use a proxy. E.g., shadowsocks, which would expose a socks5 port on localhost. It seems that nixnote does not provide with a option to use socks proxy inside the program. I hope that the program would add the proxy option because the sync speed here is too slow.

-----------------------------------------------

OK. I am wondering if any external environment variable would apply to nixnote2, since nixnote2 is just a Qt program.

**Comment by hosiet** [comment]
It seems that the standard hijacking method could apply to nixnote2. E.g., `proxychains`.

**Comment by zhtengw** [comment]
It seems that it is easy to achieve by adding a judgment statement in main.cpp. Such as 
if (global.isEnableSocks5())
    proxy.setType(QNetworkProxy::Socks5Proxy);
else
    proxy.setType(QNetworkProxy::HttpProxy);

Of course, a isEnableSocks5 function for Global class should be added.

**Comment by omaidb** [comment]
翻译水平真是屌炸天
zhtengw <notifications@github.com>于2016年11月24日 周四16:49写道：

**Comment by zhtengw** [comment]
I have tried to achieve this feature, you can find it at https://github.com/zhtengw/nixnote2/commit/b89e137407a82a5db5d9749d66f1261cbb125bca. But I don't have a situation to test whether it is work or not. If it is sure to work, I will open a pull request.

**Comment by baumgarr** [comment]
This has been merged into the base code & should be available with the next release.

**Comment by omaidb** [comment]
@hosiet thank you very much
