### ISSUE TITLE
Build on Linux: Unknown module(s) in QT: webkit webkitwidgets

### ISSUE THREAD

**Issue by Granjow** [baumgarr/nixnote2#252]
I have downloaded QtCreator and installed Qt 5.3 GCC 64bit (and also 5.7.1). When I try to compile from QtCreator, I receive this error message:

    :-1: Error: Unknown module(s) in QT: webkit webkitwidgets

Why is this? How do you build on Linux? Does Qt 5.7.1 not work at all currently?

I would like to contribute to Nixnote2, but it is a bit hard when it does not compile :) Happy for hints.

**Comment by hosiet** [comment]
If you are using Linux, it would be much easier if you install all Qt development files from your distribution. If you have trouble with installing from distribution, you may provide with your distribution name and version number. Someone may give you suggestion then.

(If you are installing manually, please note that Qt webkit is not inside official Qt release. It is provided by community since Qt 5.6. However I would strongly suggest you install related files from your distribution to get rid of those mess.)

**Comment by baumgarr** [comment]
Also, the user manual has a list of packages needed for various distribution.

**Comment by baumgarr** [comment]
No response. Closing issue.
