### ISSUE TITLE
Different fonts in notes in Evernote webclient, but only one in NixNote2

### ISSUE THREAD

**Issue by vlig** [baumgarr/nixnote2#256]
I have notes with Times and Courier fonts. Before today appearing notes was good, but today there are **only one font** in notes. From webclient - all right.
The reason maybe is I have changed some settings in nixnote, installed fontconfig-infinality and freetype2-infinality.
What is the reason of such behavior?
[webclient screenshot](http://s8.hostingkartinok.com/uploads/images/2017/01/9d5eaed38599b09b7e09152cbd83c08c.png)
[nixnote2 screenshot](http://s8.hostingkartinok.com/uploads/images/2017/01/c61c861c45fe4cf508a7178956df03b3.png)

**Comment by baumgarr** [comment]
I can't think of any reason that NixNote would be ignoring individual fonts that have already been applied. If you think it is a setting in NixNote, you can shut down NixNote, rename the ~/.nixnote/nixnote-1.conf file and restart. It will create a new nixnote-1.conf file with the default settings.

My guess would be that it has something to do with the fonts that you installed.

**Comment by vlig** [comment]
> My guess would be that it has something to do with the fonts that you installed.

I reinstalled vanilla fontconfig and freetype2 (deleted infinality) and everything all right now. Only one: last opened note showed up in wrong codepage, click on Sync refreshed to normal (in web-client is OK).

**Comment by baumgarr** [comment]
Great. 

The codepage is a different problem. For some reason Evernote doesn't always send the tags saying that a note is UTF-8 encoded. There is an option in Edit/Preferences under the debugging tab to force UTF8 encodng. It should correct the problem, but after enabling it you'll need to restart NixNote. I don't have it enabled by default because I haven't had a lot of feedback on it and I can't easily test it. In theory it should work.
