### ISSUE TITLE
An integrated markdown editor

### ISSUE THREAD

**Issue by marouni** [baumgarr/nixnote2#257]
I started using nixnote2 recently and I find it really great, but one thing that I would like to see is an integrated markdown editor. This would make text formatting easier as I'm more of a Keyboard user.
The note can be written in markdown and saved as markdown down or formatted note.

**Comment by artmg** [comment]
Hi @marouni, I already use markdown notation in some of my notes, and you are right that it _would_ be a useful enhancement. 

However this has already been considered in #92 which has been Closed, because of the effort and risk to getting a stable version release. Perhaps it might be reconsidered in the future, especially if there were some existing library that we could use to reduce the programming effort of writing yet another markdown editor from scratch. Thanks for your input.

**Comment by marouni** [comment]
+1 for getting a stable version release.
I'll close this for now and maybe reopen it later on.
Thanks,
