### ISSUE TITLE
Changes in documents do not sync

### ISSUE THREAD

**Issue by ElBarto90** [baumgarr/nixnote2#268]
When opening a pdf, docx or odt document attached to a note making changes to it, the changes do not sync. NixNote doesn't recognize any changes made to the document (Synchronized=yes).

When opening the attached document again, the changes are still visible though - it seems like nixnote is working with a local copy here.

When making inline changes to the note containing the document to force a sync (Synchronized=no), the attached file gets broken and can not be opened in evernote web or android client (document name changes to "unknown") anymore.

Latest build, Linux Mint 18.1 Cinnamon 64bit

**Comment by baumgarr** [comment]
I think I have this fixed, but the fix doesn't  make a whole lot of sense to me (from a programming standpoint). I also found another issue that I was unaware could happen that it could corrupt it because some editors don't save a file, but delete it & re-save it. That could cause NN to have problems because it would have been aware of the delete, but never the re-add. I think I have both situations corrected.

One thing to note: If you begin editing something in NN, then close NN before you save any changes, you will still have this problem. There isn't anything I can do about that. I don't have a way of knowing if something is being edited when NN shuts down and Evernote requires an accurate hash of the file when assigning an attachment or image to a note. When you edit a file that hash changes so it cannot cross reference the two.

Thanks again for the report!
