### ISSUE TITLE
Feature request: Insert Todo with [] and [x] and improvement

### ISSUE THREAD

**Issue by danielmaurer** [baumgarr/nixnote2#279]
Please, implements to Insert Todo with [] and [x] and when insert an enter in todo list insert an todo in the new line.

**Comment by baumgarr** [comment]
This probably won't happen unless someone can tell me how to implement this in Javascript. 

There are a few problems.

First, changing a [] & a [x] to a checkbox is easy. The issue is doing that and keeping the current cursor position. When I change the [] and insert the checkbox, I'm inserting characters into the document and that can cause the cursor to jump. I don't know how to do this change & re-position the cursor accurately.

The pressing Enter & inserting a checkbox is even harder. I don't have any easy way of determining if the cursor is on a line with a checkbox. It is also further complicated because I'd need to remove an empty to-do if someone presses enter twice.

Unfortunately both of these would require more complex Javascript than I'm able to do. I'll leave this open for a while in case someone wants to volunteer some assistance, but I don't see this happening any time soon.  Sorry.

**Comment by danielmaurer** [comment]
For pressing Enter & inserting a checkbox can not be based on the Bullet List?
I suggest add label "help needed".

Thanks!

**Comment by baumgarr** [comment]
No, it cannot be based on the Bullet List. 

The problem is that I don't do the code for a bullet list. This is handled by Webkit. The whole editor is just an HTML page that has a content set to editable. For a todo, it needs to insert an HTML item that isn't something that Webkit provides.

**Comment by baumgarr** [comment]
You can accomplish something like this in the next release using a Javascript exit in the next release. It allows you to edit a note based on its contents. Look in the sample_exits directory in the next release.
