### ISSUE TITLE
Volatile Window Layout

### ISSUE THREAD

**Issue by davidswords** [baumgarr/nixnote2#282]
I usually have the application setup in narrow view, however, I have noticed that when I restart, it is always back to the wide note list. All of the panels are back to their original sizes. In the notes panel, the visible columns are back to default again.

**Comment by baumgarr** [comment]
Try running from a terminal. Is it shutting down cleanly?  Also check that you have permissions to the .conf files in  ~/.nixnote

**Comment by davidswords** [comment]
Now that I think of it, it is likely the case that I haven't been shutting down cleanly. When the window is adjusted, how is that layout stored? Is it something that is stored immediately, or on exit?

**Comment by baumgarr** [comment]
It is stored on exit.

**Comment by davidswords** [comment]
So, it seems to be happening when I simply go to shutdown the computer and Nixnote2 is still open.

**Comment by baumgarr** [comment]
I never considered someone wouldn't intentionally shut the program down cleanly.  

The next release will have an option to intercept the SIGHUP so it can do a save. Until then, I'd really really recommend shutting NN down before you exit. I wouldn't be surprised if you have some data loss because things are not beings saved.
