### ISSUE TITLE
After exec on root

### ISSUE THREAD

**Issue by Beattle** [baumgarr/nixnote2#288]
After executing on root nixnote2 not started on usual user  
Error: signal 11:
nixnote2(_Z13fault_handleri+0x2e)[0x4c518e]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f05581c24b0]
/lib/x86_64-linux-gnu/libc.so.6(+0x14d43d)[0x7f05582da43d]
nixnote2(_ZN17CrossMemoryMapper5writeE10QByteArray+0x121)[0x7efea1]
nixnote2(_ZN17CrossMemoryMapper5writeE7QString+0x2f)[0x7f001f]
nixnote2(main+0x1932)[0x4c1832]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f05581ad830]
nixnote2(_start+0x29)[0x4c5089]

**Comment by baumgarr** [comment]
It looks like when you were running as root it either didn't shut down or left a memory fragment about.

When NN starts it creates a shared memory segment. This is what it checks to see if another instance is running and how it communicates. If the segment exists, it will try to free it and re-attach. If it is able to free it and it no longer exists then the previous instance crashed and it can go ahead normally. If it still exists then it thinks there is another instance running.

My guess is that because you created the instance as root it is crashing trying to free the memory segment. 

You could try one of three things:

1.) Restart it as root and do a clean stop. That may correct it. I've never tried.

2.) Logout completely & log back in. Maybe will free then, but I doubt it.

2.) Restart the PC to remove the memory segment.

**Comment by Beattle** [comment]
I see. Now after reboot it`s work
