### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by Hexcles** [baumgarr/Nixnote2#35]
I am using GNOME3 with a HiDPI screen. Since GNOME 3.12, my `Xft.dpi` is automatically set to 192 by GNOME, which is twice as the default. This seems to work well (fonts, elements are twice large) on most GTK and QT applications. However, in Nixnote2, the GUI (including the editor) does not follow the DPI setting, except for the right-click menu.

Since so many QT 4/5 applications work without problems, it does not look like a hard issue to fix. I'm currently learning QT and might try to look into it myself if I have time later.

**Comment by edgimar** [comment]
I am using beta3 on a HiDPI display, and everything is still very small.  The editor font-size doesn't seem to be able to be adjusted without also specifying a editor font-type -- it would be better to have a general scale factor (or DPI setting) that applies to everything.  By the way, when I run qtconfig, the fonts on that tool appear at a proper size.  Maybe nixnote needs to retrieve the system-wide DPI setting, and then use that?

By the way, when I change the default GUI font size, there are still some menu items that have a small size (only "Add another user" and "User account maintenance"  in the File menu are the size I've set them to -- all other items in that menu are tiny).

**Comment by baumgarr** [comment]
I don't know how to figure out how to calculate the font size, so I'd need to look into it more deeply when I have time.  The reason for specifying the font is because not all fonts can scale to the same size as other fonts.  Simply putting in a point size wouldn't work for all fonts, so I need to figure out what is available.

I think I've corrected the menus so they do reflect the proper font when you override them.  If this is still an issue after the next beta let me know.

Thanks for the help!

**Comment by edgimar** [comment]
@baumgarr the zeal project (which uses Qt) deals with this by having the user specify a minimum font size -- maybe looking at the Zeal code to see what they did might help:  https://github.com/zealdocs/zeal

**Comment by baumgarr** [comment]
You should be able to change the font size in beta 4.
