### ISSUE TITLE
Binarie files corruption between evernote client and Nixnote client

### ISSUE THREAD

**Issue by labichea** [baumgarr/nixnote2#356]
When a binary file is attached (.zip .7z or encrypted database format) to a note within Evernote Client (Windows Evernote_6.5.4720.0_x86), synchronized on Evernote servers and after  retrieved on a Nixnote2 client (/ NixNote2 - 2.0 / Windows - Beta 13).  The binary file  has exactly the same size but not the same checksum. The opposite way has no issue (Nixnote2 -> Evernote client) - binary files are not corrupted. 

My assumption is that the Evernote Clients are modifying binary files during upload synchronization. (Which algorithm ?) and reversing binary files during download synchronization. But Evernote clients don't perform this binary modification for files coming from another webservice client like Nixnote2.

**Comment by baumgarr** [comment]
Is the binary still usable?  If Evernote is modifying the file I'm not sure what can be done.

**Comment by labichea** [comment]
For example a compressed file  .zip is no longer usable and corrupted.

With an Hexa editor I took a look to this zip file, it contains lot of interesting text.  I think that it's not related to any obscur algorithm from Evernote but more a memory exhaustion from the NixNote2 Windows client. I attached a jpg with Hexa dump. Some very interesting lines are in (like _qUncompress: Input data is corrupted_). and the zip file itself.  

Some functions related to Qt5 library are dumped in this 7z file.

Summary of my tests.
Evernote client -> Nixnote2 client = KO
Nixnote2 client -> Evernote client = OK
Nixnote2 client -> Evernote WEB = OK
Evernote WEB -> Nixnote2 client = KO

![hedit hexa dump](https://user-images.githubusercontent.com/29988595/28736956-a1720782-73ec-11e7-9935-28d7a22de69d.jpg)

[Conformance WIN10 LTSB.zip](https://github.com/baumgarr/nixnote2/files/1184296/Conformance.WIN10.LTSB.zip)

**Comment by baumgarr** [comment]
I forgot that beta 13 was the Windows client.  That explains why I can't recreate this it in Linux.

The Windows client I use I can't actually sync with Evernote at the moment. Evernote's sandbox is throwing a system error, so I can't debug much on Windows at the moment. I'll try later tomorrow. The machine I use for Windows only has the sandbox server connected.

A couple of questions:

#1 How large is the file?

#2 Are you seeing corruption with any other files, like images or anything else? Every file attachment (binary or otherwise) goes through the same download process. I'd expect if it was wide spread you'd see more missing images.  The other weird thing is that it doesn't use qUncompress. It actually doesn't do anything with attachments other than tell the OS to open the default application based on the mime type.

#3 When you viewed it in the hex editor, how did you get to the file? Did you detach it, or did you go to the .nixnote\db-1\dba directory & look at it directly?

**Comment by labichea** [comment]
I will ask to your questions:

1.  my database.kdbx  (keepass encrypted passwords) is 15 kBytes. The 7-zip file is 300 kBytes. 
2.  It seems that unknown extensions are affected (at least .kdbx and .7z).  .jpg extension is not affected by this corruption issue.
3.  The corruption occurs when I am using the "Save Link..." function by right clicking on the attached file. As you suggested, I made also the tests with .nixnote\db-2\dba\xxx.bin files. They are all correct ! By copying them in another place and change them by the original name.extension, it works perfectly.

I made also a additional test on a linux machine by installing the following file nixnote2-2.0_amd64.deb. The issue is exactly the same as the Windows beta 13 version.

Alex.

**Comment by baumgarr** [comment]
Thanks for the clear steps on the problem. That should help me recreate it. I was missing the "Save Link" piece of the puzzle. I was just opening them from within NixNote. I'll try again to recreate it and let you know.

Thanks!

**Comment by baumgarr** [comment]
Thanks for the report. It is fixed and should be uploaded to GitHub later today. Thanks!

**Comment by baumgarr** [comment]
I forgot you are not building it from source. If you don't want to wait until I do a new release, you can send me an email & I'll send you a new binary.

Also, I should have mentioned. Don't edit files in the .nixnote/dba directory directly. It can cause problems because the hash file will change.

Thanks.
