### ISSUE TITLE
Auto Checkboxes when doing Checkbox lists

### ISSUE THREAD

**Issue by grisu48** [baumgarr/nixnote2#376]
I would like to propose a feature, that is common in the Mac and Windows Client of Evernote.

When editing Checkboxes and I press Return, the client automatically adds a new Checkbox.
I find this quiet handy when creating Todolists, otherwise the click-and-point work increases significantly.

Thank you!

**Comment by baumgarr** [comment]
You're not the first person to request this, but I haven't found a way to accomplish it. I'm not that adept at JavasScript so that I can tell if the cursor is on the same line as a checkbox.

About the best solution I can provide is to upgrade to the latest release. In that release there is an example exit which would create a checkbox when it saw a [] in a note.

Sorry.

**Comment by grisu48** [comment]
Thank you for your response! I really appreciate your efforts on the program.
Keep it going, I love it!
