### ISSUE TITLE
[RFE] Add Ctrl-N keyboard shortcut for New Text Note

### ISSUE THREAD

**Issue by fastcat** [baumgarr/Nixnote2#47]
This seems like a natural keyboard shortcut, but it doesn't seem to be bound

**Comment by baumgarr** [comment]
Thanks for the report.  It is a bug.  It should be Ctrl+N and will be fixed in the next release.  Just an FYI, you can override any shortcut by copying /usr/share/nixnote2/shortcuts.txt to ~/.nixnote/ and changing any defaults.  The shortcut for File_Note_Add, however, won't work until the next release.
