### ISSUE TITLE
Error updating to version 2.1.1.r3

### ISSUE THREAD

**Issue by omarcoaur3lio** [baumgarr/Nixnote2#470]
I'm bumping into this problem when trying to update nixnote2-git in archlinux:
==> Iniciando build()...
patching file src/html/enmlformatter.cpp
patching file src/main.cpp
Project MESSAGE: nixnote2: Release build!
Project MESSAGE: nixnote2: Compiler version 8
Project MESSAGE: nixnote2: Adding compiler config g++8
Project MESSAGE: Target binary: qmake-build-release/nixnote2
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets
==> ERRO: Uma falha ocorreu em build().
    Abortando...
:: Unable to build nixnote2-git - makepkg exited with code: 4

**Comment by robert7** [comment]
hi
as I don't use Arch, can't help you much directly..

But I suppose, the problem you have, has something to do with: Qt you are using has not installed "webkit" module.
Webkit was only available until Qt 5.5, but for Debian and Ubuntu there is a comunnity version until the newest version (incl. Ubuntu 19.04).
Not sure about Arch through.. Are you using system default Qt? If yes, then maybe someway you can install the webkit package..

Actually now I see the the packaging contains a "qt5-webkit" package, which should be installed as dependency..
https://aur.archlinux.org/packages/nixnote2-git/ - Dependencies
Webkit: https://www.archlinux.org/packages/?q=qt5-webkit

The packaging for Arch was done by @HaleTom ...maybe he can help you more. But it seems problem is with configuration of your system.
 
PS: if the problem is with nixnote v2.1 pls next time open a issue in https://github.com/robert7/nixnote2 as this upstream repository is currently unmaintained.

**Comment by sgtmarcoaurelio** [comment]
hi
so I have these modules installed, even had the previous version of nixnote installed without any problem

**Comment by omarcoaur3lio** [comment]
hi
so I have these modules installed, even had the previous version of nixnote installed without any problem

**Comment by robert7** [comment]
OK. I have no idea. The compiler error message says, it can't find Qt modules "webkit webkitwidgets".

**Comment by robert7** [comment]
But if you can't compile yourself, you can always use the prebuild AppImage version. This should work on your system out of the box. https://github.com/robert7/nixnote2/releases/tag/continuous
Just download the file, mark as executable and run.
More info here: https://github.com/robert7/nixnote2/wiki/HowTo---Run-AppImage
