### ISSUE TITLE
Create NixNote2 ebuild to install on Gentoo

### ISSUE THREAD

**Issue by maffblaster** [baumgarr/nixnote2#63]
I'm creating this task for myself. I will create an ebuild to install NixNote 2 on Gentoo. Hopefully I will be able to find more bugs in this process. :smile:

**Comment by baumgarr** [comment]
Awesome!  Thanks for the help!

**Comment by Maffblaster** [comment]
No problem. I've definitely started the work...

**Comment by mroess** [comment]
I wrote an ebuild for my self: 

https://github.com/mroess/overlay/blob/master/app-misc/nixnote/nixnote-2.0_beta4.ebuild

I have no experience what so ever in writing ebuilds, but it works for me. I have no idea if the ebuild covers all decencies. Feel free to use and/or enhance it.

**Comment by baumgarr** [comment]
Thanks.  I'll add it to the project.

Stupid question #1.  I'm not familiar with Gentoo and its package format.  Other than including the file do I need to do anything else or do I need to build a source tarball and distribute it or do people get the source directly from GitHub?

**Comment by mroess** [comment]
Gentoo (normally) has no pre-build binaries like .deb or .rpm. An ebuild
is just a instruction for the gentoo package management where to
download the source and how to compile it on your local machine.

So actually you don't even need to put it in the repository. People must
add this ebuild manually to there system or use a tool called layman to
add it.

A note that an ebuild exists and a link to it might be enough. People
will then download the source directly from GitHub and build and install
it locally.

Am 23.10.2015 um 15:48 schrieb baumgarr:

**Comment by baumgarr** [comment]
Awesome.  Thanks!

**Comment by baumgarr** [comment]
I've uploaded the file to SourceForge.  I've also added some packaging scripts to the project so when I build the deb/rpm/tar files I can build a new ebuild.

Thanks for the help!

**Comment by Maffblaster** [comment]
@baumgarr Since I'm doing stuff for Gentoo I should be able to manage Gentoo packaging entirely. I should have some time this weekend to finish up my work. :)

**Comment by baumgarr** [comment]
Ok.  Do you want me to delete the one that I uploaded to SourceForge or leave it alone for now?

**Comment by Maffblaster** [comment]
@baumgarr I'm encountering a slight difficulties when unpacking the source from the ebuild I'm working on. Could you rename the repository on here to start with a lower case N instead of the capital N is currently has? I know this seems crazy, but it creates problems cause the package name is lowercase when I download it (`nixnote-2.0_beta`), but when I extract the source from GitHub's auto-generated tarball it renamed to `Nixnote-2.0_beta`. I think this is because the repository is uppercase.

Since case doesn't matter in the URL the change doesn't effect anyone's git repos (people can still push and pull correctly), but it <i>will</i> effect anyone who's trying to auto-build based on git tags using GitHub's generated tarballs. I'm probably the only one doing this so far; it would best to fix it early. :)

Let me know if this isn't possible. I can get around it...but it would be all around better if you just make the N lower case.

**Comment by zhtengw** [comment]
The ebuild for nixnote was just accept by gentoo-zh, any gentoo user can emerge it after you add gentoo-zh overlay.
```bash
layman -a gentoo-zh
```

**Comment by baumgarr** [comment]
Thanks. Is this still an issue that needs to remain open, or do I just put a note in a file with the layman command like I do with PuppyLinux.txt?

Sorry. I'm not very familiar with Gentoo.  

Thanks again.

**Comment by zhtengw** [comment]
@baumgarr You can write a Gentoo.txt with the same info as what I add in README.md.

**Comment by baumgarr** [comment]
Cool. Thanks again for the help! I appreciate it.!
