### ISSUE TITLE
Pasting evernote url does not work

### ISSUE THREAD

**Issue by cmiramon** [baumgarr/Nixnote2#83]
I'm using nixnote2-beta4 on Ubuntu 14.04 LTS

1) right-click on a note, copy url
2) create a new note
3) paste does nothing, paste as unformated text, paste the text of the link

**Comment by baumgarr** [comment]
I can't recreate this.  Was the note synchronized?  If you copy the note link from the note list window does it work?

**Comment by cmiramon** [comment]
Copying the note link from the note list windows works but from the note windows it does not.

**Comment by baumgarr** [comment]
Weird.  They both go through the same paste logic.  The only difference is the fact that it is pulling the note URL from a different source.  Since the unformatted paste has the contents, the source doesn't appear to be the issue.  Are you using the button, menu option, or shortcut to paste?  There are issues with shortcuts in beta 4 that the next release fixes.

**Comment by cmiramon** [comment]
I confirm the bug with the shortcut, the button and the menu option. The bug is also present for Nixnote2 in French and in English.

I could try to compile trunk nex week. When I tried it, I could compile and run the program but the authorization screen did not work, it was blank and did not show the evernote authorization.

**Comment by baumgarr** [comment]
I don't recall anything since beta 4 that would alter the behavior of the paste, so I'm not sure compiling from the source tree will help.  I was more wondering if it was just the shortcut that had the problem, but if the shortcut and the button and the menu have the problem it is something else.

Try looking at the source of the note after the paste with the "view/source" menu option.  Is there anything unusual?

**Comment by cmiramon** [comment]
Now it works ! Mystery.

I cannot find a recipe to trigger the bug. If I find it, I'll reopen an issue.
