### ISSUE TITLE
Unable to update note.  Invalid note structure : 

### ISSUE THREAD

**Issue by jeffbuhrt** [baumgarr/Nixnote2#84]
@baumgarr #27 is still broken in Beta4 beyond/related what we looked at in #210. 
[I was torn between adding onto one of those threads waiting feedback from other users or starting a new ticket.]
[Links to Dropbox copies of the .nnex because github won't allow them to be attached.]

https://www.dropbox.com/s/knlrymq1qvy7gd4/note_fails.nnex?dl=0
-Note where I couldn't delete some formatting added that was added from an Android added note

Another longer intentionally text note that fails when added via a paste from Thunderbird directly into Nixnote2 Beta4 (Fedora 22 x86_64).
https://www.dropbox.com/s/vxihnob6mz1homw/free-pasted-via-www.nnex?dl=0
-works fine pasted to www.evernote.com and then updated in Nixnote2

https://www.dropbox.com/s/xnimbr1yw9kba1g/free-test2.nnex?dl=0
-fails even after some cleanups

**Comment by baumgarr** [comment]
Thanks.  I'll take a look at it and see what I can find.

**Comment by baumgarr** [comment]
Pasting directly from a web browser or another program can be problematic because the paste doesn't always produce valid HTML.  Some things can be lost along the way which can alter the structure of the note.  I always recommend using the web clipper from Evernote, then doing a sync.

In the first note, you have a non-printable character.  That is causing the sync problem.  Looking at it in VIM, there is a bad character just before the last <span> tag.

^[<span style="background-color: rgb(255, 255, 255); font-size: 13px; line-height: 17px;">Nothing
is more dangerous than an idea, when it's the only one we have.-
Alain</span></div>

If you go to View/Show Source you should be able to remove this. 

I didn't have any issues with the second note.  When a note fails to sync NN will just stop syncing, so I'm guessing that fixing the first will allow the second to sync.

**Comment by baumgarr** [comment]
*sigh*.  Sorry.  It interpreted the tags I entered.  The not-printable character is just before the last span tag (the one with style="background-color: rgb(255, 255, 255); font-size: 13px; line-height: 17px;).

**Comment by jeffbuhrt** [comment]
@baumgarr  it isn't that *I* didn't get around the problems, but maybe a better way to protect the user from not being able to sync again then give up using Nixnote. As for the one note, I am not sure the Escape was the problem but something else. I wonder if anything except printables should be stripped the the Evernote API can't handle them... The question is what happens to others in NLS & DBCS languages?

**Comment by baumgarr** [comment]
I'm pretty sure I'd mess up other non-English languages.  I've done so in the past with seemingly minor changes.  The good news is that NN2 is better at handling this than NN1, so I'm getting better at finding things.  

Thanks for the help!
