### ISSUE TITLE
idle cpu usage seems to have increased between beta 3 and beta 4

### ISSUE THREAD

**Issue by axfelix** [baumgarr/Nixnote2#90]
went from nothing to a tiny bit, basically. I've reverted for now.

**Comment by baumgarr** [comment]
It will naturally be a bit higher.  In the past it would only index a note after it hasn't changed for 5 minutes.  That caused problems because the background thread to index could consume a lot of CPU and lead to DB locks.  Now it indexes every time it saves.  That can cause some additional overhead, but overall the program should be more responsive.

**Comment by axfelix** [comment]
Ah, OK! That's fine -- I thought it was doing something *constantly*, not every time it saves. This behaviour sounds smart. Sorry for the confusion.

**Comment by axfelix** [comment]
Background CPU usage still seems to be creeping upward...
