### ISSUE TITLE
Support a markdown edit mode

### ISSUE THREAD

**Issue by JPvRiel** [baumgarr/nixnote2#92]
A great enhancement would be hacking in support for using markdown. NixNote already features 'Note HTML Source'. The trick would be to convert markdown into an HTML format evernote accepts (I'm guessing this is how marxi.co does it).

The marxi.co example which has become a paid for product: https://marxi.co/
CuteMarkEd (https://github.com/cloose/CuteMarkEd) gives nice insight into how evernote could have a markdown edit mode for notes.

I've so wished evernote would improve note formatting, but they seem hell bent on hacking in tons of bloatware instead of refining how notes are formatted. Evernote formatting is dodgy at best. It's awful for documenting any code snippets (arguably, that's what a gist is for, etc). But apart from code, markdown provides a way for consistent formatting to be applied (i.e. styles and typesetting) instead of being stuck with a word 95 like formatting tools.

Arguably other services, like gist, is a better place to store notes for those who like markdown.

**Comment by baumgarr** [comment]
I'll leave this open for a little while to think about it, but I don't see any way to do it gracefully.  

There are a lot of problems with doing this.  I think Marxi is getting around the problems by forcing the edits on their site, so they are maintaining a copy on their site and a copy on Evernote.  If you edit it on Evernote and then Marxi, my guess is that you'll overwrite the Evernote copy.

I've only come up with these ways of handling it, but none of them are good.

1.) Only allow markdown until a note is synchronized, then don't allow it.  After that you'd be forced to use the "normal" editing modes.
2.) Maintain another copy of the note in markdown and ignore any changes mode on Evernote.  If you edit it on Evernote then in NixNote, the Evernote changes would be lost.
3.) Maintain another copy of the note in markdown and if it is edited outside of NixNote change it so that markdown isn't permitted.
4.) Keep the note in markdown in Evernote and only display it properly on NixNote.  This would allow you to edit anywhere, but you'd only see the results in NixNote.
5.) Only permit a very limited text-only or customized subset of markdown and take a lot of control over when it can be used.  I don't even want to think about the problems that would cause.

None of them are particularly attractive and that doesn't even get into the headache of attachments (which would be very ugly to maintain) or the effort to integrate another editor mode and markdown conversion.

**Comment by JPvRiel** [comment]
Fair enough, the challenge is reading the html and converting back to markdown. I briefly thought about including the original markdown embedded for diff/comparison to deal with edits outside of markdown, but as an HTML comment CDATA tag block, but I imagine the evernote note format might not like that...

**Comment by artmg** [comment]
@JPvRiel [geeknote](http://www.geeknote.me/) allows you to sync your notes locally in Markdown format, allowing you to edit them with a markdown editor, then push changes back up. Perhaps this could be a solution for your requirement? 

Alternatively, @baumgarr, if you ever wanted to implement such a feature request, then perhaps you could check out how geeknote does it?
 
FYI I already use geeknote myself, to compliment NixNote2, as a way to "export" notes _individually_ so they can be crawled by my local search engine (as well as being a backup).

**Comment by baumgarr** [comment]
I didn't know that geeknote existed.  It is similar to what I wanted to do with nixnote2-cmd, but geeknote is much farther along.

**Comment by JPvRiel** [comment]
@artmg thank you, geeknote looks useful I plan to check out geeknote and test it.

I briefly tried hacking around with the HTML source for notes (e.g. directly copied the output of a .md to .html conversion, but it seems evernote is quite picky. Would be nice to inspect how geeknote handles it.

**Comment by baumgarr** [comment]
I've given this some thought & I don't want to implement it at this time because I'm afraid of the complexity.  Maybe in the future after 2.0 is released I'll revisit this idea but I'm really trying to keep changes to a minimum to avoid introducing new bugs prior to the 2.0 release.

FWIW, you can do some manipulation of notes via the command line with NixNote.  It doesn't allow for markdown, but you can do some cool things.

**Comment by userpixel** [comment]
Any chance to implement this feature?
I use NixNote on a daily basis as a part of my brain and am quite dependent on it.
However, I want to convert my notes to markdown and save it as a Git repo as well.
There are some ways to achieve this using Evernote but they all require installing Evernote (which is not supported on Linux).
It would be great if a basic markdown export is added to nixnote that supports:

H1/H2 headers
Bold/Italic text
Links
UL/OL (unordered lists and ordered lists)
Images (the image can be exported next to the note with the same name as the note file name postfixed with -img1.jpg, etc.)

**Comment by baumgarr** [comment]
Probably not in the immediate future. The problem I have is in editing an existing note. I'd need a way to convert HTML back to markdown. I've been toying with the way for users to write their own macros & exits to NixNote to allow them to add any utilities they wish (and take the workload off me) but the last few months have been incredibly busy for me.

**Comment by danielmaurer** [comment]
I would like of this feature.

**Comment by JPvRiel** [comment]
> need a way to convert HTML back to markdown

When looking into helping out with this and experimenting, I bumped my head against the same issue. I even thought about trying to find a way to hide the original markdown within an html/xml comment, but it felt messy and I gave up... Partly, I gave up because I think evernote does some weird things and it's not treated fully as html, so I failed to get that working.

**Comment by baumgarr** [comment]
You could do a limited markdown by using exits to convert from markdown when saving, but converting it back would still be a problem.
